name: Bot Scraper
on:
  schedule:
    - cron: '0 * * * *' 
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Force Install Dependencies
        run: npm install axios puppeteer
      
      - name: Install Chrome for Puppeteer
        run: npx puppeteer browsers install chrome
      
      - name: Run Scraper
        run: node index.js
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          FB_COOKIES: ${{ secrets.FB_COOKIES }}
          
      - name: Commit changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add last_posts.json || echo "No changes"
          git commit -m "Update memory" || exit 0
          git push
